import { db, libsqlClient } from './client';
import { accounts } from './schema';
import { runMigrations } from './migrate';

const now = Date.now();

const seedAccounts = [
  {
    id: 'seed-intuit',
    name: 'Intuit',
    industry: 'Financial Software',
    state: 'CA',
    status: 'Active POC',
    fortune_500: true,
    fortune_1000: true,
    open_opps: 1,
    last_activity: '2026-05-15',
    prior_context: 'Active POC with the identity security team. Evaluating NHI and workforce identity coverage. Strong technical champion in cloud security.',
    website: 'https://www.intuit.com',
    linkedin_url: null,
    sf_id: null,
    amount: 285000,
    archived: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'seed-lennar',
    name: 'Lennar Corporation',
    industry: 'Real Estate and Construction',
    state: 'FL',
    status: 'Active POC',
    fortune_500: true,
    fortune_1000: true,
    open_opps: 1,
    last_activity: '2026-05-12',
    prior_context: 'POC kicked off in Q1. Focus on securing cloud service accounts and contractor access sprawl post-acquisition.',
    website: 'https://www.lennar.com',
    linkedin_url: null,
    sf_id: null,
    amount: 195000,
    archived: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'seed-fiserv',
    name: 'Fiserv',
    industry: 'Financial Technology',
    state: 'WI',
    status: 'Champion Building',
    fortune_500: true,
    fortune_1000: true,
    open_opps: 1,
    last_activity: '2026-05-08',
    prior_context: 'Working on internal champion post-discovery. Strong PCI compliance angle. Need to engage EB before next QBR.',
    website: 'https://www.fiserv.com',
    linkedin_url: null,
    sf_id: null,
    amount: 320000,
    archived: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'seed-kaiser',
    name: 'Kaiser Permanente',
    industry: 'Healthcare',
    state: 'CA',
    status: 'Evaluation',
    fortune_500: false,
    fortune_1000: true,
    open_opps: 1,
    last_activity: '2026-05-01',
    prior_context: 'Inbound from cloud security team. HIPAA compliance driver. Evaluating two vendors side by side through June.',
    website: 'https://www.kaiserpermanente.org',
    linkedin_url: null,
    sf_id: null,
    amount: 410000,
    archived: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'seed-tmobile',
    name: 'T-Mobile',
    industry: 'Telecommunications',
    state: 'WA',
    status: 'Expansion',
    fortune_500: true,
    fortune_1000: true,
    open_opps: 1,
    last_activity: '2026-04-28',
    prior_context: 'Existing customer. Expansion into DevOps use case and secrets management. Renewal also up in Q3.',
    website: 'https://www.t-mobile.com',
    linkedin_url: null,
    sf_id: null,
    amount: 140000,
    archived: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'seed-marriott',
    name: 'Marriott International',
    industry: 'Hospitality',
    state: 'MD',
    status: 'Prospect',
    fortune_500: true,
    fortune_1000: true,
    open_opps: 0,
    last_activity: '2026-04-15',
    prior_context: 'Outbound from field event. Security team expressed interest in NHI after breach coverage. Need to book discovery.',
    website: 'https://www.marriott.com',
    linkedin_url: null,
    sf_id: null,
    amount: null,
    archived: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'seed-fedex',
    name: 'FedEx',
    industry: 'Logistics and Transportation',
    state: 'TN',
    status: 'Stalled',
    fortune_500: true,
    fortune_1000: true,
    open_opps: 1,
    last_activity: '2026-03-20',
    prior_context: 'Had strong momentum in Q4 but champion went on extended leave. Need to re-engage and find new internal sponsor.',
    website: 'https://www.fedex.com',
    linkedin_url: null,
    sf_id: null,
    amount: 225000,
    archived: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'seed-cardinal',
    name: 'Cardinal Health',
    industry: 'Healthcare Distribution',
    state: 'OH',
    status: 'Active POC',
    fortune_500: true,
    fortune_1000: true,
    open_opps: 1,
    last_activity: '2026-05-10',
    prior_context: 'POC phase 2 with CISO engaged. Focus on third-party vendor access and supply chain risk. Board-level visibility.',
    website: 'https://www.cardinalhealth.com',
    linkedin_url: null,
    sf_id: null,
    amount: 365000,
    archived: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'seed-pge',
    name: 'Pacific Gas and Electric',
    industry: 'Utilities',
    state: 'CA',
    status: 'Discovery',
    fortune_500: true,
    fortune_1000: true,
    open_opps: 1,
    last_activity: '2026-05-05',
    prior_context: 'Initial discovery call with cloud security team. OT/IT convergence and NERC CIP compliance are primary drivers.',
    website: 'https://www.pge.com',
    linkedin_url: null,
    sf_id: null,
    amount: null,
    archived: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'seed-dow',
    name: 'Dow Chemical',
    industry: 'Chemical Manufacturing',
    state: 'MI',
    status: 'Champion Building',
    fortune_500: true,
    fortune_1000: true,
    open_opps: 1,
    last_activity: '2026-04-22',
    prior_context: 'Building internal business case. Identity sprawl from 2023 SAP migration is the key driver. IAM team is the champion.',
    website: 'https://www.dow.com',
    linkedin_url: null,
    sf_id: null,
    amount: 175000,
    archived: false,
    created_at: now,
    updated_at: now,
  },
];

async function main() {
  await runMigrations();

  for (const account of seedAccounts) {
    await db.insert(accounts).values(account).onConflictDoNothing();
  }

  console.log(`Seeded ${seedAccounts.length} accounts.`);
  libsqlClient.close();
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
